// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package me.heyteacher.flutter_antplus.bikepower.pigeons

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object BikepowerEventChannelPigeonUtils {
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

enum class AntplusDataSource(val raw: Int) {
  POWER_ONLY_DATA(0),
  WHEEL_TORQUE_DATA(1),
  CRANK_TORQUE_DATA(2),
  CTF_DATA(3),
  COAST_OR_STOP_DETECTED(4),
  INITIAL_VALUE_POWER_ONLY_DATA(5),
  INITIAL_VALUE_WHEEL_TORQUE_DATA(6),
  INITIAL_VALUE_CRANK_TORQUE_DATA(7),
  INITIAL_VALUE_CTF_DATA(8),
  INVALID(9),
  INVALID_CTF_CAL_REQ(10),
  UNRECOGNIZED(11);

  companion object {
    fun ofRaw(raw: Int): AntplusDataSource? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class AntplusBatteryStatus(val raw: Int) {
  NEW_STATUS(0),
  GOOD(1),
  OK(2),
  LOW(3),
  CRITICAL(4),
  INVALID(5),
  UNRECOGNIZED(6);

  companion object {
    fun ofRaw(raw: Int): AntplusBatteryStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AntplusPedalSmoothnessData (
  val separatePedalSmoothnessSupport: Boolean,
  val leftOrCombinedPedalSmoothness: Double? = null,
  val rightPedalSmoothness: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AntplusPedalSmoothnessData {
      val separatePedalSmoothnessSupport = pigeonVar_list[0] as Boolean
      val leftOrCombinedPedalSmoothness = pigeonVar_list[1] as Double?
      val rightPedalSmoothness = pigeonVar_list[2] as Double
      return AntplusPedalSmoothnessData(separatePedalSmoothnessSupport, leftOrCombinedPedalSmoothness, rightPedalSmoothness)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      separatePedalSmoothnessSupport,
      leftOrCombinedPedalSmoothness,
      rightPedalSmoothness,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AntplusPedalSmoothnessData
    return BikepowerEventChannelPigeonUtils.deepEquals(this.separatePedalSmoothnessSupport, other.separatePedalSmoothnessSupport) && BikepowerEventChannelPigeonUtils.deepEquals(this.leftOrCombinedPedalSmoothness, other.leftOrCombinedPedalSmoothness) && BikepowerEventChannelPigeonUtils.deepEquals(this.rightPedalSmoothness, other.rightPedalSmoothness)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BikepowerEventChannelPigeonUtils.deepHash(this.separatePedalSmoothnessSupport)
    result = 31 * result + BikepowerEventChannelPigeonUtils.deepHash(this.leftOrCombinedPedalSmoothness)
    result = 31 * result + BikepowerEventChannelPigeonUtils.deepHash(this.rightPedalSmoothness)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AntplusTorqueEffectivenessData (
  val leftTorqueEffectiveness: Double? = null,
  val rightTorqueEffectiveness: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AntplusTorqueEffectivenessData {
      val leftTorqueEffectiveness = pigeonVar_list[0] as Double?
      val rightTorqueEffectiveness = pigeonVar_list[1] as Double
      return AntplusTorqueEffectivenessData(leftTorqueEffectiveness, rightTorqueEffectiveness)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      leftTorqueEffectiveness,
      rightTorqueEffectiveness,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AntplusTorqueEffectivenessData
    return BikepowerEventChannelPigeonUtils.deepEquals(this.leftTorqueEffectiveness, other.leftTorqueEffectiveness) && BikepowerEventChannelPigeonUtils.deepEquals(this.rightTorqueEffectiveness, other.rightTorqueEffectiveness)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BikepowerEventChannelPigeonUtils.deepHash(this.leftTorqueEffectiveness)
    result = 31 * result + BikepowerEventChannelPigeonUtils.deepHash(this.rightTorqueEffectiveness)
    return result
  }
}
private open class BikepowerEventChannelPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AntplusDataSource.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AntplusBatteryStatus.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AntplusPedalSmoothnessData.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AntplusTorqueEffectivenessData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AntplusDataSource -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is AntplusBatteryStatus -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is AntplusPedalSmoothnessData -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is AntplusTorqueEffectivenessData -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val BikepowerEventChannelPigeonMethodCodec = StandardMethodCodec(BikepowerEventChannelPigeonCodec())


private class BikepowerEventChannelPigeonStreamHandler<T>(
    val wrapper: BikepowerEventChannelPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface BikepowerEventChannelPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class OnPowerDataStreamHandler : BikepowerEventChannelPigeonEventChannelWrapper<Long> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: OnPowerDataStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.bikepower.EventChannelMethods.onPowerData"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = BikepowerEventChannelPigeonStreamHandler<Long>(streamHandler)
      EventChannel(messenger, channelName, BikepowerEventChannelPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from BikepowerEventChannelPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<Long>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class OnCadenceDataStreamHandler : BikepowerEventChannelPigeonEventChannelWrapper<Long> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: OnCadenceDataStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.bikepower.EventChannelMethods.onCadenceData"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = BikepowerEventChannelPigeonStreamHandler<Long>(streamHandler)
      EventChannel(messenger, channelName, BikepowerEventChannelPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from BikepowerEventChannelPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<Long>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class OnBalanceDataStreamHandler : BikepowerEventChannelPigeonEventChannelWrapper<Long> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: OnBalanceDataStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.bikepower.EventChannelMethods.onBalanceData"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = BikepowerEventChannelPigeonStreamHandler<Long>(streamHandler)
      EventChannel(messenger, channelName, BikepowerEventChannelPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from BikepowerEventChannelPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<Long>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class OnPedalSmoothnessDataStreamHandler : BikepowerEventChannelPigeonEventChannelWrapper<AntplusPedalSmoothnessData> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: OnPedalSmoothnessDataStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.bikepower.EventChannelMethods.onPedalSmoothnessData"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = BikepowerEventChannelPigeonStreamHandler<AntplusPedalSmoothnessData>(streamHandler)
      EventChannel(messenger, channelName, BikepowerEventChannelPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from BikepowerEventChannelPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<AntplusPedalSmoothnessData>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class OnTorqueEffectivenessDataStreamHandler : BikepowerEventChannelPigeonEventChannelWrapper<AntplusTorqueEffectivenessData> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: OnTorqueEffectivenessDataStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.bikepower.EventChannelMethods.onTorqueEffectivenessData"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = BikepowerEventChannelPigeonStreamHandler<AntplusTorqueEffectivenessData>(streamHandler)
      EventChannel(messenger, channelName, BikepowerEventChannelPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from BikepowerEventChannelPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<AntplusTorqueEffectivenessData>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class OnBatteryStatusDataStreamHandler : BikepowerEventChannelPigeonEventChannelWrapper<AntplusBatteryStatus> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: OnBatteryStatusDataStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.bikepower.EventChannelMethods.onBatteryStatusData"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = BikepowerEventChannelPigeonStreamHandler<AntplusBatteryStatus>(streamHandler)
      EventChannel(messenger, channelName, BikepowerEventChannelPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from BikepowerEventChannelPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<AntplusBatteryStatus>) {}

override fun onCancel(p0: Any?) {}
}
      
