name: flutter_antplus
description: "Flutter plugin for Ant+: search, listen, acquire data from Ant+ sensors like power meters, heart rate and cadence sensors"
version: 0.6.5+15
repository: https://codeberg.org/heyteacher/flutter_antplus
license: BSD 3-Clause
issue_tracker: https://codeberg.org/heyteacher/flutter_antplus/issues
homepage: https://codeberg.org/heyteacher/flutter_antplus
documentation: https://codeberg.org/heyteacher/flutter_antplus
topics: [flutter, antplus, powermeter, heartrate, cadence]
funding: [https://liberapay.com/heyteacher]

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0
  meta: ^1.18.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_heyteacher_meta: ^7.9.0+183
  flutter_test:
    sdk: flutter
  pigeon: ^27.3.0
  very_good_analysis: ^10.3.0

flutter:
  plugin:
    platforms:
      android:
        package: me.heyteacher.flutter_antplus
        pluginClass: AntplusFlutterPlugin
