// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package me.heyteacher.flutter_antplus.device.pigeons

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object DeviceEventChannelPigeonUtils {
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

enum class AntplusDeviceType(val raw: Int) {
  HEARTRATE(0),
  BIKEPOWER(1),
  CADENCE(2);

  companion object {
    fun ofRaw(raw: Int): AntplusDeviceType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class AntplusDeviceState(val raw: Int) {
  DEAD(0),
  CLOSED(1),
  SEARCHING(2),
  TRACKING(3),
  PROCESSING_REQUEST(4),
  UNRECOGNIZED(5);

  companion object {
    fun ofRaw(raw: Int): AntplusDeviceState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class AntplusRequestAccessResult(val raw: Int) {
  SUCCESS(0),
  USER_CANCELLED(1),
  CHANNEL_NOT_AVAILABLE(2),
  OTHER_FAILURE(3),
  DEPENDENCY_NOT_INSTALLED(4),
  DEVICE_ALREADY_IN_USE(5),
  SEARCH_TIMEOUT(6),
  ALREADY_SUBSCRIBED(7),
  BAD_PARAMS(8),
  ADAPTER_NOT_DETECTED(9),
  UNRECOGNIZED(10);

  companion object {
    fun ofRaw(raw: Int): AntplusRequestAccessResult? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AntplusDevice (
  val number: Long,
  val name: String,
  val type: AntplusDeviceType
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AntplusDevice {
      val number = pigeonVar_list[0] as Long
      val name = pigeonVar_list[1] as String
      val type = pigeonVar_list[2] as AntplusDeviceType
      return AntplusDevice(number, name, type)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      number,
      name,
      type,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AntplusDevice
    return DeviceEventChannelPigeonUtils.deepEquals(this.number, other.number) && DeviceEventChannelPigeonUtils.deepEquals(this.name, other.name) && DeviceEventChannelPigeonUtils.deepEquals(this.type, other.type)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + DeviceEventChannelPigeonUtils.deepHash(this.number)
    result = 31 * result + DeviceEventChannelPigeonUtils.deepHash(this.name)
    result = 31 * result + DeviceEventChannelPigeonUtils.deepHash(this.type)
    return result
  }
  override fun toString(): String {
    return "AntplusDevice(number=$number, name=$name, type=$type)"
  }
}
private open class DeviceEventChannelPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AntplusDeviceType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AntplusDeviceState.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AntplusRequestAccessResult.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AntplusDevice.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AntplusDeviceType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is AntplusDeviceState -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is AntplusRequestAccessResult -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is AntplusDevice -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val DeviceEventChannelPigeonMethodCodec = StandardMethodCodec(DeviceEventChannelPigeonCodec())


private class DeviceEventChannelPigeonStreamHandler<T>(
    val wrapper: DeviceEventChannelPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface DeviceEventChannelPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class OnScanResultStreamHandler : DeviceEventChannelPigeonEventChannelWrapper<AntplusDevice> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: OnScanResultStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.device.EventChannelMethods.onScanResult"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = DeviceEventChannelPigeonStreamHandler<AntplusDevice>(streamHandler)
      EventChannel(messenger, channelName, DeviceEventChannelPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from DeviceEventChannelPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<AntplusDevice>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class OnRequestAccessResultStreamHandler : DeviceEventChannelPigeonEventChannelWrapper<AntplusRequestAccessResult> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: OnRequestAccessResultStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.device.EventChannelMethods.onRequestAccessResult"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = DeviceEventChannelPigeonStreamHandler<AntplusRequestAccessResult>(streamHandler)
      EventChannel(messenger, channelName, DeviceEventChannelPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from DeviceEventChannelPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<AntplusRequestAccessResult>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class OnDeviceStateChangeStreamHandler : DeviceEventChannelPigeonEventChannelWrapper<AntplusDeviceState> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: OnDeviceStateChangeStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.device.EventChannelMethods.onDeviceStateChange"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = DeviceEventChannelPigeonStreamHandler<AntplusDeviceState>(streamHandler)
      EventChannel(messenger, channelName, DeviceEventChannelPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from DeviceEventChannelPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<AntplusDeviceState>) {}

override fun onCancel(p0: Any?) {}
}
      
