// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package me.heyteacher.flutter_antplus.heartrate.pigeons

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object HeartrateEventChannelPigeonUtils {
}
private open class HeartrateEventChannelPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}

val HeartrateEventChannelPigeonMethodCodec = StandardMethodCodec(HeartrateEventChannelPigeonCodec())


private class HeartrateEventChannelPigeonStreamHandler<T>(
    val wrapper: HeartrateEventChannelPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface HeartrateEventChannelPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class OnHeartRateDataStreamHandler : HeartrateEventChannelPigeonEventChannelWrapper<Long> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: OnHeartRateDataStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.heartrate.EventChannelMethods.onHeartRateData"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = HeartrateEventChannelPigeonStreamHandler<Long>(streamHandler)
      EventChannel(messenger, channelName, HeartrateEventChannelPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from HeartrateEventChannelPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<Long>) {}

override fun onCancel(p0: Any?) {}
}
      
