// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package me.heyteacher.flutter_antplus.heartrate;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class HeartratePigeon {
  static boolean pigeonDoubleEquals(double a, double b) {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (a == 0.0 ? 0.0 : a) == (b == 0.0 ? 0.0 : b) || (Double.isNaN(a) && Double.isNaN(b));
  }

  static boolean pigeonFloatEquals(float a, float b) {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (a == 0.0f ? 0.0f : a) == (b == 0.0f ? 0.0f : b) || (Float.isNaN(a) && Float.isNaN(b));
  }

  static int pigeonDoubleHashCode(double d) {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    if (d == 0.0) {
      d = 0.0;
    }
    long bits = Double.doubleToLongBits(d);
    return (int) (bits ^ (bits >>> 32));
  }

  static int pigeonFloatHashCode(float f) {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    if (f == 0.0f) {
      f = 0.0f;
    }
    return Float.floatToIntBits(f);
  }

  static boolean pigeonDeepEquals(Object a, Object b) {
    if (a == b) { return true; }
    if (a == null || b == null) { return false; }
    if (a instanceof byte[] && b instanceof byte[]) {
      return Arrays.equals((byte[]) a, (byte[]) b);
    }
    if (a instanceof int[] && b instanceof int[]) {
      return Arrays.equals((int[]) a, (int[]) b);
    }
    if (a instanceof long[] && b instanceof long[]) {
      return Arrays.equals((long[]) a, (long[]) b);
    }
    if (a instanceof double[] && b instanceof double[]) {
      double[] da = (double[]) a;
      double[] db = (double[]) b;
      if (da.length != db.length) {
        return false;
      }
      for (int i = 0; i < da.length; i++) {
        if (!pigeonDoubleEquals(da[i], db[i])) {
          return false;
        }
      }
      return true;
    }
    if (a instanceof List && b instanceof List) {
      List<?> listA = (List<?>) a;
      List<?> listB = (List<?>) b;
      if (listA.size() != listB.size()) { return false; }
      for (int i = 0; i < listA.size(); i++) {
        if (!pigeonDeepEquals(listA.get(i), listB.get(i))) {
          return false;
        }
      }
      return true;
    }
    if (a instanceof Map && b instanceof Map) {
      Map<?, ?> mapA = (Map<?, ?>) a;
      Map<?, ?> mapB = (Map<?, ?>) b;
      if (mapA.size() != mapB.size()) { return false; }
      for (Map.Entry<?, ?> entryA : mapA.entrySet()) {
        Object keyA = entryA.getKey();
        Object valueA = entryA.getValue();
        boolean found = false;
        for (Map.Entry<?, ?> entryB : mapB.entrySet()) {
          Object keyB = entryB.getKey();
          if (pigeonDeepEquals(keyA, keyB)) {
            Object valueB = entryB.getValue();
            if (pigeonDeepEquals(valueA, valueB)) {
              found = true;
              break;
            } else {
              return false;
            }
          }
        }
        if (!found) {
          return false;
        }
      }
      return true;
    }
    if (a instanceof Double && b instanceof Double) {
      return pigeonDoubleEquals((double) a, (double) b);
    }
    if (a instanceof Float && b instanceof Float) {
      return pigeonFloatEquals((float) a, (float) b);
    }
    return a.equals(b);
  }

  static int pigeonDeepHashCode(Object value) {
    if (value == null) { return 0; }
    if (value instanceof byte[]) {
      return Arrays.hashCode((byte[]) value);
    }
    if (value instanceof int[]) {
      return Arrays.hashCode((int[]) value);
    }
    if (value instanceof long[]) {
      return Arrays.hashCode((long[]) value);
    }
    if (value instanceof double[]) {
      double[] da = (double[]) value;
      int result = 1;
      for (double d : da) {
        result = 31 * result + pigeonDoubleHashCode(d);
      }
      return result;
    }
    if (value instanceof List) {
      int result = 1;
      for (Object item : (List<?>) value) {
        result = 31 * result + pigeonDeepHashCode(item);
      }
      return result;
    }
    if (value instanceof Map) {
      int result = 0;
      for (Map.Entry<?, ?> entry : ((Map<?, ?>) value).entrySet()) {
        result += ((pigeonDeepHashCode(entry.getKey()) * 31) ^ pigeonDeepHashCode(entry.getValue()));
      }
      return result;
    }
    if (value instanceof Object[]) {
      int result = 1;
      for (Object item : (Object[]) value) {
        result = 31 * result + pigeonDeepHashCode(item);
      }
      return result;
    }
    if (value instanceof Double) {
      return pigeonDoubleHashCode((double) value);
    }
    if (value instanceof Float) {
      return pigeonFloatHashCode((float) value);
    }
    return value.hashCode();
  }


  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  @NonNull
  protected static FlutterError createConnectionError(@NonNull String channelName) {
    return new FlutterError("channel-error",  "Unable to establish connection on channel: " + channelName + ".", "");
  }

  @Target(METHOD)
  @Retention(CLASS)
  @interface CanIgnoreReturnValue {}

  public enum AntplusDeviceState {
    DEAD(0),
    CLOSED(1),
    SEARCHING(2),
    TRACKING(3),
    PROCESSING_REQUEST(4),
    UNRECOGNIZED(5);

    final int index;

    AntplusDeviceState(final int index) {
      this.index = index;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class AntplusDevice {
    private @NonNull Long number;

    public @NonNull Long getNumber() {
      return number;
    }

    public void setNumber(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"number\" is null.");
      }
      this.number = setterArg;
    }

    private @NonNull String name;

    public @NonNull String getName() {
      return name;
    }

    public void setName(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"name\" is null.");
      }
      this.name = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    AntplusDevice() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      AntplusDevice that = (AntplusDevice) o;
      return pigeonDeepEquals(number, that.number) && pigeonDeepEquals(name, that.name);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), number, name};
      return pigeonDeepHashCode(fields);
    }

    public static final class Builder {

      private @Nullable Long number;

      @CanIgnoreReturnValue
      public @NonNull Builder setNumber(@NonNull Long setterArg) {
        this.number = setterArg;
        return this;
      }

      private @Nullable String name;

      @CanIgnoreReturnValue
      public @NonNull Builder setName(@NonNull String setterArg) {
        this.name = setterArg;
        return this;
      }

      public @NonNull AntplusDevice build() {
        AntplusDevice pigeonReturn = new AntplusDevice();
        pigeonReturn.setNumber(number);
        pigeonReturn.setName(name);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(2);
      toListResult.add(number);
      toListResult.add(name);
      return toListResult;
    }

    static @NonNull AntplusDevice fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      AntplusDevice pigeonResult = new AntplusDevice();
      Object number = pigeonVar_list.get(0);
      pigeonResult.setNumber((Long) number);
      Object name = pigeonVar_list.get(1);
      pigeonResult.setName((String) name);
      return pigeonResult;
    }
  }

  private static class PigeonCodec extends StandardMessageCodec {
    public static final PigeonCodec INSTANCE = new PigeonCodec();

    private PigeonCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 129: {
          Object value = readValue(buffer);
          return value == null ? null : AntplusDeviceState.values()[((Long) value).intValue()];
        }
        case (byte) 130:
          return AntplusDevice.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof AntplusDeviceState) {
        stream.write(129);
        writeValue(stream, value == null ? null : ((AntplusDeviceState) value).index);
      } else if (value instanceof AntplusDevice) {
        stream.write(130);
        writeValue(stream, ((AntplusDevice) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }


  /** Asynchronous error handling return type for non-nullable API method returns. */
  public interface Result<T> {
    /** Success case callback method for handling returns. */
    void success(@NonNull T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for nullable API method returns. */
  public interface NullableResult<T> {
    /** Success case callback method for handling returns. */
    void success(@Nullable T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for void API method returns. */
  public interface VoidResult {
    /** Success case callback method for handling returns. */
    void success();

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface HeartrateHostApi {

    void startScan();

    void stopScan();

    void connect(@NonNull Long deviceNumber);

    void disconnect();

    /** The codec used by HeartrateHostApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    /**Sets up an instance of `HeartrateHostApi` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable HeartrateHostApi api) {
      setUp(binaryMessenger, "", api);
    }
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @NonNull String messageChannelSuffix, @Nullable HeartrateHostApi api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.heartrate.HeartrateHostApi.startScan" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  api.startScan();
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.heartrate.HeartrateHostApi.stopScan" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  api.stopScan();
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.heartrate.HeartrateHostApi.connect" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                Long deviceNumberArg = (Long) args.get(0);
                try {
                  api.connect(deviceNumberArg);
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.heartrate.HeartrateHostApi.disconnect" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  api.disconnect();
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  /** Generated class from Pigeon that represents Flutter messages that can be called from Java. */
  public static class HeartrateFlutterApi {
    private final @NonNull BinaryMessenger binaryMessenger;
    private final String messageChannelSuffix;

    public HeartrateFlutterApi(@NonNull BinaryMessenger argBinaryMessenger) {
      this(argBinaryMessenger, "");
    }
    public HeartrateFlutterApi(@NonNull BinaryMessenger argBinaryMessenger, @NonNull String messageChannelSuffix) {
      this.binaryMessenger = argBinaryMessenger;
      this.messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
    }

    /**
     * Public interface for sending reply.
     * The codec used by HeartrateFlutterApi.
     */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    public void onScanResult(@NonNull AntplusDevice deviceArg, @NonNull VoidResult result) {
      final String channelName = "dev.flutter.pigeon.heartrate.HeartrateFlutterApi.onScanResult" + messageChannelSuffix;
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(
              binaryMessenger, channelName, getCodec());
      channel.send(
          new ArrayList<>(Collections.singletonList(deviceArg)),
          channelReply -> {
            if (channelReply instanceof List) {
              List<Object> listReply = (List<Object>) channelReply;
              if (listReply.size() > 1) {
                result.error(new FlutterError((String) listReply.get(0), (String) listReply.get(1), listReply.get(2)));
              } else {
                result.success();
              }
            }  else {
              result.error(createConnectionError(channelName));
            } 
          });
    }
    public void onHeartRateData(@NonNull Long rpmArg, @NonNull VoidResult result) {
      final String channelName = "dev.flutter.pigeon.heartrate.HeartrateFlutterApi.onHeartRateData" + messageChannelSuffix;
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(
              binaryMessenger, channelName, getCodec());
      channel.send(
          new ArrayList<>(Collections.singletonList(rpmArg)),
          channelReply -> {
            if (channelReply instanceof List) {
              List<Object> listReply = (List<Object>) channelReply;
              if (listReply.size() > 1) {
                result.error(new FlutterError((String) listReply.get(0), (String) listReply.get(1), listReply.get(2)));
              } else {
                result.success();
              }
            }  else {
              result.error(createConnectionError(channelName));
            } 
          });
    }
    public void onDeviceStateChange(@NonNull AntplusDeviceState stateArg, @NonNull VoidResult result) {
      final String channelName = "dev.flutter.pigeon.heartrate.HeartrateFlutterApi.onDeviceStateChange" + messageChannelSuffix;
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(
              binaryMessenger, channelName, getCodec());
      channel.send(
          new ArrayList<>(Collections.singletonList(stateArg)),
          channelReply -> {
            if (channelReply instanceof List) {
              List<Object> listReply = (List<Object>) channelReply;
              if (listReply.size() > 1) {
                result.error(new FlutterError((String) listReply.get(0), (String) listReply.get(1), listReply.get(2)));
              } else {
                result.success();
              }
            }  else {
              result.error(createConnectionError(channelName));
            } 
          });
    }
  }
}
