// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, omit_local_variable_types, omit_obvious_local_variable_types

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum DataSource {
  powerOnlyData,
  wheelTorqueData,
  crankTorqueData,
  ctfData,
  coastOrStopDetected,
  initialValuePowerOnlyData,
  initialValueWheelTorqueData,
  initialValueCrankTorqueData,
  initialValueCtfData,
  invalid,
  invalidCtfCalReq,
  unrecognized,
}

enum BatteryStatus {
  newStatus,
  good,
  ok,
  low,
  critical,
  invalid,
  unrecognized,
}

class PedalSmoothnessData {
  PedalSmoothnessData({
    required this.separatePedalSmoothnessSupport,
    this.leftOrCombinedPedalSmoothness,
    required this.rightPedalSmoothness,
  });

  bool separatePedalSmoothnessSupport;

  double? leftOrCombinedPedalSmoothness;

  double rightPedalSmoothness;

  List<Object?> _toList() {
    return <Object?>[
      separatePedalSmoothnessSupport,
      leftOrCombinedPedalSmoothness,
      rightPedalSmoothness,
    ];
  }

  Object encode() {
    return _toList();  }

  static PedalSmoothnessData decode(Object result) {
    result as List<Object?>;
    return PedalSmoothnessData(
      separatePedalSmoothnessSupport: result[0]! as bool,
      leftOrCombinedPedalSmoothness: result[1] as double?,
      rightPedalSmoothness: result[2]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PedalSmoothnessData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(separatePedalSmoothnessSupport, other.separatePedalSmoothnessSupport) && _deepEquals(leftOrCombinedPedalSmoothness, other.leftOrCombinedPedalSmoothness) && _deepEquals(rightPedalSmoothness, other.rightPedalSmoothness);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class TorqueEffectivenessData {
  TorqueEffectivenessData({
    this.leftTorqueEffectiveness,
    required this.rightTorqueEffectiveness,
  });

  double? leftTorqueEffectiveness;

  double rightTorqueEffectiveness;

  List<Object?> _toList() {
    return <Object?>[
      leftTorqueEffectiveness,
      rightTorqueEffectiveness,
    ];
  }

  Object encode() {
    return _toList();  }

  static TorqueEffectivenessData decode(Object result) {
    result as List<Object?>;
    return TorqueEffectivenessData(
      leftTorqueEffectiveness: result[0] as double?,
      rightTorqueEffectiveness: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TorqueEffectivenessData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(leftTorqueEffectiveness, other.leftTorqueEffectiveness) && _deepEquals(rightTorqueEffectiveness, other.rightTorqueEffectiveness);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is DataSource) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is BatteryStatus) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is PedalSmoothnessData) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is TorqueEffectivenessData) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : DataSource.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : BatteryStatus.values[value];
      case 131:
        return PedalSmoothnessData.decode(readValue(buffer)!);
      case 132:
        return TorqueEffectivenessData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

Stream<int> onPowerData( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel onPowerDataChannel =
      EventChannel('dev.flutter.pigeon.bikepower.EventChannelMethods.onPowerData$instanceName', pigeonMethodCodec);
  return onPowerDataChannel.receiveBroadcastStream().map((dynamic event) {
    return event as int;
  });
}
    
Stream<int> onCadenceData( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel onCadenceDataChannel =
      EventChannel('dev.flutter.pigeon.bikepower.EventChannelMethods.onCadenceData$instanceName', pigeonMethodCodec);
  return onCadenceDataChannel.receiveBroadcastStream().map((dynamic event) {
    return event as int;
  });
}
    
Stream<int> onBalanceData( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel onBalanceDataChannel =
      EventChannel('dev.flutter.pigeon.bikepower.EventChannelMethods.onBalanceData$instanceName', pigeonMethodCodec);
  return onBalanceDataChannel.receiveBroadcastStream().map((dynamic event) {
    return event as int;
  });
}
    
Stream<PedalSmoothnessData> onPedalSmoothnessData( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel onPedalSmoothnessDataChannel =
      EventChannel('dev.flutter.pigeon.bikepower.EventChannelMethods.onPedalSmoothnessData$instanceName', pigeonMethodCodec);
  return onPedalSmoothnessDataChannel.receiveBroadcastStream().map((dynamic event) {
    return event as PedalSmoothnessData;
  });
}
    
Stream<TorqueEffectivenessData> onTorqueEffectivenessData( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel onTorqueEffectivenessDataChannel =
      EventChannel('dev.flutter.pigeon.bikepower.EventChannelMethods.onTorqueEffectivenessData$instanceName', pigeonMethodCodec);
  return onTorqueEffectivenessDataChannel.receiveBroadcastStream().map((dynamic event) {
    return event as TorqueEffectivenessData;
  });
}
    
Stream<BatteryStatus> onBatteryStatusData( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel onBatteryStatusDataChannel =
      EventChannel('dev.flutter.pigeon.bikepower.EventChannelMethods.onBatteryStatusData$instanceName', pigeonMethodCodec);
  return onBatteryStatusDataChannel.receiveBroadcastStream().map((dynamic event) {
    return event as BatteryStatus;
  });
}
    
