// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, omit_local_variable_types, omit_obvious_local_variable_types

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum AntplusDeviceType {
  heartrate,
  bikepower,
  cadence,
}

enum AntplusDeviceState {
  dead,
  closed,
  searching,
  tracking,
  processingRequest,
  unrecognized,
}

enum AntplusRequestAccessResult {
  success,
  userCancelled,
  channelNotAvailable,
  otherFailure,
  dependencyNotInstalled,
  deviceAlreadyInUse,
  searchTimeout,
  alreadySubscribed,
  badParams,
  adapterNotDetected,
  unrecognized,
}

class AntplusDevice {
  AntplusDevice({
    required this.number,
    required this.name,
    required this.type,
  });

  int number;

  String name;

  AntplusDeviceType type;

  List<Object?> _toList() {
    return <Object?>[
      number,
      name,
      type,
    ];
  }

  Object encode() {
    return _toList();  }

  static AntplusDevice decode(Object result) {
    result as List<Object?>;
    return AntplusDevice(
      number: result[0]! as int,
      name: result[1]! as String,
      type: result[2]! as AntplusDeviceType,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AntplusDevice || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(number, other.number) && _deepEquals(name, other.name) && _deepEquals(type, other.type);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AntplusDevice(number: $number, name: $name, type: $type)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is AntplusDeviceType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is AntplusDeviceState) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is AntplusRequestAccessResult) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is AntplusDevice) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : AntplusDeviceType.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : AntplusDeviceState.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : AntplusRequestAccessResult.values[value];
      case 132:
        return AntplusDevice.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

/// Returns a broadcast [Stream] of events from the `onScanResult` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<AntplusDevice> onScanResult( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel onScanResultChannel =
      EventChannel('dev.flutter.pigeon.device.EventChannelMethods.onScanResult$instanceName', pigeonMethodCodec);
  return onScanResultChannel.receiveBroadcastStream().map((dynamic event) {
    return event as AntplusDevice;
  });
}
    
/// Returns a broadcast [Stream] of events from the `onRequestAccessResult` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<AntplusRequestAccessResult> onRequestAccessResult( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel onRequestAccessResultChannel =
      EventChannel('dev.flutter.pigeon.device.EventChannelMethods.onRequestAccessResult$instanceName', pigeonMethodCodec);
  return onRequestAccessResultChannel.receiveBroadcastStream().map((dynamic event) {
    return event as AntplusRequestAccessResult;
  });
}
    
/// Returns a broadcast [Stream] of events from the `onDeviceStateChange` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<AntplusDeviceState> onDeviceStateChange( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel onDeviceStateChangeChannel =
      EventChannel('dev.flutter.pigeon.device.EventChannelMethods.onDeviceStateChange$instanceName', pigeonMethodCodec);
  return onDeviceStateChangeChannel.receiveBroadcastStream().map((dynamic event) {
    return event as AntplusDeviceState;
  });
}
    
